import AxeBuilder from "@axe-core/playwright"
import { expect, test, type Page } from "@playwright/test"

const expectPageReflow = async (page: Page): Promise<void> => {
  const dimensions = await page.evaluate(() => ({
    viewport: document.documentElement.clientWidth,
    document: document.documentElement.scrollWidth,
    body: document.body.scrollWidth
  }))
  expect(dimensions.document).toBeLessThanOrEqual(dimensions.viewport)
  expect(dimensions.body).toBeLessThanOrEqual(dimensions.viewport)
}

for (const path of ["/", "/exams/", "/atlas/", "/practice/", "/review/", "/simulations/", "/offline/", "/settings/", "/report/"]) {
  test(`the redesigned ${path} page reflows and has accessible mobile navigation`, async ({ page }) => {
    await page.setViewportSize({ height: 720, width: 320 })
    await page.goto(path)
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
    const navigation = page.getByRole("navigation", { name: "Primary", exact: true })
    await expect(navigation).toBeVisible()
    await expect(navigation.getByRole("link", { name: "Practice", exact: true })).toBeVisible()
    await expect(page.locator(".site-header").getByRole("link", { name: "Settings", exact: true })).toBeVisible()
    await expect(page.locator(".site-header a[href='/offline/'], .site-header a[href='/transparency/'], .exam-chip")).toHaveCount(0)
    await expectPageReflow(page)

    await navigation.locator("summary").click()
    await expect(navigation.getByRole("link", { name: /^Tool atlas/ })).toBeVisible()
    await expect(navigation.getByRole("link", { name: /^Hazard scenes/ })).toBeVisible()
    await expectPageReflow(page)

    const scan = await new AxeBuilder({ page })
      .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"])
      .analyze()
    expect(scan.violations
      .filter(({ impact }) => impact === "critical" || impact === "serious")
      .map(({ id, nodes }) => ({ id, targets: nodes.map(({ target }) => target) })))
      .toEqual([])
  })
}

test("Library supports keyboard dismissal, outside clicks, and normal link navigation", async ({ page }) => {
  await page.goto("/")
  const menu = page.locator("[data-library-menu]")
  const trigger = menu.locator("summary")
  await trigger.focus()
  await page.keyboard.press("Enter")
  await page.keyboard.press("Tab")
  await expect(menu.getByRole("link", { name: /^Tool atlas/ })).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(trigger).toBeFocused()
  await expect(menu).not.toHaveAttribute("open")
  await trigger.click()
  await page.mouse.click(8, 400)
  await expect(menu).not.toHaveAttribute("open")
  await trigger.click()
  await menu.getByRole("link", { name: /^Hazard scenes/ }).click()
  await expect(page).toHaveURL(/\/hazards\/$/)
})

test("enlarged text keeps Settings on the right and the Library panel within the viewport", async ({ page }) => {
  for (const width of [320, 800, 900, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto("/")
    await page.evaluate(() => document.documentElement.setAttribute("data-large-text", ""))
    await page.locator("[data-library-menu] summary").click()
    await expectPageReflow(page)
    const header = await page.locator(".site-header-inner").boundingBox()
    const settings = await page.locator(".nav-utility").boundingBox()
    expect(header).not.toBeNull()
    expect(settings).not.toBeNull()
    expect(settings!.x + settings!.width).toBeCloseTo(width < 768 ? width : header!.x + header!.width, 0)
  }
})

test("Library links and Settings downloads remain reachable without JavaScript", async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 320, height: 720 } })
  const page = await context.newPage()
  await page.goto("/")
  const navigation = page.getByRole("navigation", { name: "Primary", exact: true })
  await navigation.locator("summary").click()
  await expect(navigation.getByRole("link", { name: /^Hazard scenes/ })).toBeVisible()
  await expectPageReflow(page)
  await page.locator(".site-header").getByRole("link", { name: "Settings", exact: true }).click()
  await expect(page.getByRole("link", { name: "Manage offline downloads", exact: true })).toHaveAttribute("href", "/offline/")
  await expect(page.locator(".site-footer").getByRole("link", { name: "Sources and methods", exact: true })).toBeVisible()
  await context.close()
})

test("atlas family controls filter the released tools and restore the selected family", async ({ page }) => {
  await page.setViewportSize({ height: 720, width: 320 })
  await page.goto("/atlas/")
  const familyTabs = page.getByRole("tablist", { name: "Visual family", includeHidden: true })
  await expect(familyTabs).toBeHidden()
  const familySelect = page.getByRole("combobox", { name: "Family", exact: true })
  await expect(familySelect).toBeVisible()
  await expect(familySelect.getByRole("option")).toHaveCount(10)
  const family = familyTabs.locator('[data-atlas-family]:not([data-atlas-family="all"])').first()
  const familyName = await family.getAttribute("data-atlas-family")
  expect(familyName).not.toBeNull()
  const expected = await page.locator("[data-tool-family]").evaluateAll((cards, selectedFamily) =>
    cards.filter((card) => card.getAttribute("data-tool-family") === selectedFamily).length,
  familyName)
  expect(expected).toBeGreaterThan(0)

  await familySelect.selectOption(familyName!)
  await expect(family).toHaveAttribute("aria-selected", "true")
  await expect(page.locator("[data-tool-family]:visible")).toHaveCount(expected)
  await expect(page.locator("[data-atlas-count]")).toContainText(`Showing ${expected} illustrated`)
  expect(new URL(page.url()).searchParams.get("family")).toBe(familyName)
  await expectPageReflow(page)

  await page.reload()
  await expect(family).toHaveAttribute("aria-selected", "true")
  await expect(page.locator("[data-tool-family]:visible")).toHaveCount(expected)
  await page.setViewportSize({ width: 1248, height: 900 })
  await expect(familyTabs).toBeVisible()
  await expect(familySelect).toBeHidden()
  await family.focus()
  await page.keyboard.press("Home")
  const all = familyTabs.getByRole("tab", { name: /^All families/ })
  await expect(all).toBeFocused()
  await expect(all).toHaveAttribute("aria-selected", "true")
  expect(new URL(page.url()).searchParams.has("family")).toBe(false)
  await expect(page.locator("[data-tool-family]:visible")).toHaveCount(await page.locator("[data-tool-family]").count())
})

test("exam search, record selection, and detail tabs use the published records", async ({ page }) => {
  await page.setViewportSize({ height: 720, width: 320 })
  await page.goto("/exams/")
  const search = page.getByRole("searchbox", { name: "Search announcements and study plans" })
  await expect(search).toBeVisible()
  const rows = page.locator("[data-exam-row]")
  const total = await rows.count()
  expect(total).toBeGreaterThan(0)
  const firstChoice = page.locator("[data-exam-choice]").first()
  const recordId = await firstChoice.getAttribute("data-exam-choice")
  const title = (await firstChoice.locator("strong").textContent())?.trim() ?? ""
  expect(title.length).toBeGreaterThan(0)
  await search.fill(title)
  await firstChoice.click()
  expect(new URL(page.url()).searchParams.get("record")).toBe(recordId)
  const panel = page.locator("[data-exam-panel]:visible")
  await expect(panel).toHaveCount(1)
  await expect(panel).toBeFocused()
  await expect(panel.getByRole("link", { name: "See what practice covers", exact: true })).toHaveAttribute("href", "/practice/#covers")
  const subjectTab = panel.getByRole("tab", { name: "What it tests", exact: true })
  await subjectTab.click()
  await expect(subjectTab).toHaveAttribute("aria-selected", "true")
  await expect(panel.getByRole("tabpanel", { name: "What it tests" })).toBeVisible()
  await expectPageReflow(page)

  await search.fill("no-such-published-custodian-exam")
  await expect(page.locator("[data-exam-row]:visible")).toHaveCount(0)
  await expect(page.locator("[data-exam-empty]")).toBeVisible()
  await expect(page.locator("[data-exam-panel]:visible")).toHaveCount(0)
  expect(new URL(page.url()).searchParams.has("record")).toBe(false)
  await page.getByRole("button", { name: "Clear filters", exact: true }).click()
  await expect(search).toBeFocused()
  await expect(search).toHaveValue("")
  await expect(page.locator("[data-exam-row]:visible")).toHaveCount(total)
  const coverage = rows.first().locator(".exam-card-coverage").getByRole("link", { name: "See what practice covers", exact: true })
  await expect(coverage).toBeVisible()
  await coverage.click()
  await expect(page).toHaveURL(/\/practice\/#covers$/)
  await expect(page.locator("#covers")).toBeFocused()
  await expect(page.locator("#study-coverage-heading")).toBeInViewport()
})

test("compact navigation stays at the viewport bottom and all Library destinations resolve", async ({ page }) => {
  await page.setViewportSize({ width: 384, height: 800 })
  await page.goto("/practice/")
  await expect(page.getByRole("heading", { name: "Start with a set of 45.", exact: true })).toBeVisible()
  const primary = page.getByRole("navigation", { name: "Primary", exact: true })
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
  const bar = await primary.boundingBox()
  expect(bar!.y + bar!.height).toBe(800)
  await primary.locator("summary").click()
  const panel = page.locator(".nav-popover")
  const sheet = await panel.boundingBox()
  expect(sheet!.x).toBe(0)
  expect(sheet!.width).toBe(384)
  expect(Math.abs(sheet!.y + sheet!.height - bar!.y)).toBeLessThanOrEqual(1)
  await panel.getByRole("link", { name: /^Tool comparisons/ }).click()
  await expect(page.locator("#comparisons")).toBeInViewport()
  await page.locator("[data-library-menu] summary").click()
  await page.locator(".nav-popover").getByRole("link", { name: /^What practice covers/ }).click()
  await expect(page.getByRole("heading", { name: "What practice covers", exact: true })).toBeInViewport()
})

test("Atlas preserves written records when released illustrations cannot load", async ({ page }) => {
  await page.route("**/content/**", async (route) => {
    if (route.request().resourceType() === "image") await route.abort()
    else await route.continue()
  })
  await page.setViewportSize({ width: 384, height: 800 })
  await page.goto("/atlas/")
  const firstCard = page.locator("[data-tool-family]").first()
  await expect(firstCard.locator("[data-atlas-image-notice]")).toBeVisible()
  const description = await firstCard.locator("img").getAttribute("alt")
  expect(description).toBeTruthy()
  await expect(firstCard.locator("[data-atlas-image-notice]")).toContainText(description!)
  await expect(firstCard.getByRole("link")).toBeVisible()
  await expect(page.getByRole("combobox", { name: "Family", exact: true })).toBeEnabled()
  await expectPageReflow(page)
})


test("exam cycle keeps the responsive reading order and sources without JavaScript", async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    for (const width of [1248, 384]) {
      await page.setViewportSize({ width, height: 900 })
      await page.goto("/exams/")
      const cycle = page.locator("#exams-cycle")
      await expect(cycle.locator(".timeline > li:visible")).toHaveCount(width === 384 ? 3 : 4)
      await expect(cycle.locator('.timeline time[datetime="2026-08-22"]')).toHaveCount(1)
      await expect(cycle.locator('.timeline time[datetime="2026-07-05"]').locator("..")).toContainText(/Jericho/)
      const notice = cycle.locator("[data-administration-state]:visible")
      await expect(notice).toHaveCount(1)
      const noticeBox = await notice.boundingBox()
      const datesBox = await cycle.locator(".timeline").boundingBox()
      expect(noticeBox).not.toBeNull()
      expect(datesBox).not.toBeNull()
      if (width === 384) expect(noticeBox!.y).toBeLessThan(datesBox!.y)
      else expect(noticeBox!.y).toBeGreaterThan(datesBox!.y)
      await cycle.getByText("Sources and review dates", { exact: true }).click()
      await expect(cycle.locator("details .proof-line")).toBeVisible()
      expect(await cycle.locator("details a:visible").count()).toBeGreaterThan(0)
      await expectPageReflow(page)
    }
  } finally { await context.close() }
})

test("filing filters compose with search, restore from the URL, and never select a study exam", async ({ page }) => {
  await page.setViewportSize({ width: 384, height: 900 })
  await page.goto("/exams/?filing=closed")
  const before = await page.evaluate(() => JSON.stringify({ ...localStorage }))
  const filters = page.getByRole("group", { name: "Filing status at source review" })
  const rows = page.locator("[data-exam-row]:visible")
  await expect(filters.getByRole("button", { name: "Filing closed", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(rows).toHaveCount(2)
  const search = page.getByRole("searchbox")
  await search.fill("promotion")
  await expect(rows).toHaveCount(1)
  await page.locator("[data-exam-choice]:visible").click()
  await expect(page.locator("[data-exam-panel]:visible")).toHaveCount(1)
  await filters.getByRole("button", { name: "Plan only", exact: true }).click()
  await expect(rows).toHaveCount(0)
  await expect(page.locator("[data-exam-panel]:visible")).toHaveCount(0)
  expect(new URL(page.url()).searchParams.has("record")).toBe(false)
  await page.getByRole("button", { name: "Clear filters", exact: true }).click()
  await expect(search).toBeFocused()
  await expect(rows).toHaveCount(3)
  await filters.getByRole("button", { name: "Plan only", exact: true }).click()
  await expect(rows).toHaveCount(1)
  await page.reload()
  await expect(rows).toHaveCount(1)
  await filters.getByRole("button", { name: "Open for filing", exact: true }).click()
  await expect(rows).toHaveCount(0)
  await expect(page.locator("[data-exam-empty]")).toBeVisible()
  await expect(page.locator("[data-exam-prompt]")).toBeHidden()
  await expectPageReflow(page)
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage }))).toBe(before)
})
