import { expect, test } from "@playwright/test"

test("custom practice preserves the chosen length and saves exact feedback for Review", async ({ page }) => {
  await page.goto("/practice/")
  const builder = page.getByRole("region", { name: "Build a practice set" })
  await expect(builder).toBeVisible()
  await builder.getByRole("checkbox", { name: /^Cleaning tools/ }).uncheck()
  await builder.getByRole("checkbox", { name: /^Minor maintenance/ }).uncheck()
  await builder.getByRole("checkbox", { name: /^Mixed-domain/ }).uncheck()
  await expect(builder.getByRole("button", { name: "Start this practice set" })).toBeDisabled()
  await expect(builder.getByRole("status")).toContainText("5 questions match")
  await builder.getByRole("radio", { name: "5 questions — all matching" }).check()
  await builder.getByRole("checkbox", { name: /^Cleaning tools/ }).check()
  await expect(builder.getByRole("radio", { name: "5 questions", exact: true })).toBeChecked()
  await builder.getByText("Repeat a set", { exact: true }).click()
  await builder.getByLabel("Set code", { exact: true }).fill("browser-custom")
  await builder.getByRole("button", { name: "Start this practice set" }).click()
  await expect(page.locator(".player-position")).toHaveText("Question 1 of 5 · Text version")
  await expect(page.getByRole("link", { name: "Skip for now", exact: true })).toHaveAttribute("href", /position=2$/)
  const firstUrl = page.url()
  expect(firstUrl).toContain("?set=pb1.")
  await page.getByRole("button", { name: "Flag for review", exact: true }).click()
  await page.getByRole("radio").first().check()
  await page.getByRole("button", { name: "Save answer", exact: true }).click()
  await expect(page.locator(".feedback-rationales")).toBeVisible()
  await page.getByRole("link", { name: "Next question", exact: true }).click()
  await expect(page.locator(".player-position")).toHaveText("Question 2 of 5 · Text version")
  await page.getByRole("link", { name: "← Previous question", exact: true }).click()
  await expect(page.locator(".feedback-rationales")).toBeVisible()
  await page.goto("/review/")
  const explanation = page.getByRole("link", { name: "Read explanation", exact: true }).first()
  await expect(explanation).toHaveAttribute("href", new URL(firstUrl).pathname + new URL(firstUrl).search)
  await explanation.click()
  await expect(page.locator(".feedback-rationales")).toBeVisible()
})

test("an invalid custom set link cannot fall through to a normal answer form", async ({ page }) => {
  await page.goto("/practice/")
  const href = await page.locator("[data-study-hub] .study-hero a.button-primary").getAttribute("href")
  await page.goto(`${href}?set=pb1.1.45.0000&position=1`)
  await expect(page.getByRole("heading", { name: "This practice set is unavailable" })).toBeVisible()
  await expect(page.getByRole("button", { name: "Save answer", exact: true })).toHaveCount(0)
})

test("setup navigation connects Practice, Hazard drill and Simulation with real links", async ({ page }) => {
  await page.goto("/practice/#practice-builder")
  const navigation = page.getByRole("navigation", { name: "Practice setup", exact: true })
  await expect(navigation.getByRole("link", { name: "Practice set", exact: true })).toHaveAttribute("aria-current", "page")
  await navigation.getByRole("link", { name: "Hazard drill", exact: true }).click()
  await expect(page).toHaveURL(/\/hazards\/$/)
  await expect(navigation.getByRole("link", { name: "Hazard drill", exact: true })).toHaveAttribute("aria-current", "page")
  await navigation.getByRole("link", { name: "Full simulation", exact: true }).click()
  await expect(navigation.getByRole("link", { name: "Full simulation", exact: true })).toHaveAttribute("aria-current", "page")
  await navigation.getByRole("link", { name: "Practice set", exact: true }).click()
  await expect(page.getByRole("region", { name: "Build a practice set" })).toBeVisible()
})

test("custom question documents remain available offline with reordered set parameters", async ({ page, context }) => {
  await page.goto("/practice/")
  await page.getByRole("region", { name: "Build a practice set" }).getByRole("button", { name: "Start this practice set" }).click()
  await expect(page.locator(".player-position")).toHaveText("Question 1 of 45 · Text version")
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  // First navigation may precede worker activation. Reload under its control
  // so this actual document is cached through the service worker fetch path.
  await page.reload()
  await expect(page.getByRole("button", { name: "Save answer", exact: true })).toBeVisible()
  const url = new URL(page.url())
  const set = url.searchParams.get("set")!
  url.search = `?position=1&set=${set}`
  await context.setOffline(true)
  await page.goto(url.href)
  await expect(page.locator(".player-position")).toHaveText("Question 1 of 45 · Text version")
  await expect(page.getByRole("button", { name: "Save answer", exact: true })).toBeVisible()
})
